name: chexnet
channels:
  - conda-forge
  - defaults
dependencies:
  - tensorflow
  - tensorflow-datasets=4.4.0
  - tensorflow-gpu
  - jupyterlab
  - ipywidgets
  - ipykernel
  - iprogress
  - matplotlib
  - pandas