name: chexnet
channels:
  - conda-forge
  - defaults
dependencies:
  - tensorflow
  - tensorflow-datasets=4.4.0
  - tensorflow-gpu
  - jupyterlab
  - ipywidgets
  - ipykernel
  - iprogress
  - matplotlib
  - pandas
  - pip:
    - https://github.com/tmarkmann/tfds-cxr14/archive/refs/heads/main.zip